### PR TITLE
Repository Cleanup

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
Please check the **[Preview]**.

<br>

### Changes

- Added license badge
- Added board badge
- General formatting / spacing
- Fixed up warnings / wrong const usage
- Moved source code into source folder
- Moved into `DIYCharger` to please Arduino IDE
  
  *Consider PlatformIO if you don't like this~*

<br>

### Repository Suggestions

- Add tags

- Disable unused widgets:
  - `Packages`
  - `Releases`

- Disable unused tabs:
  - `Projects
  - `Actions`
  - `Wiki` 

[Preview]: https://github.com/ElectronicsArchiver/DIY-BatteryCharger-18650

### CODE REVIEW

**Comment by shor-ty** [comment]
Hey, I am wondering how you found my repository so fast? I simply uploaded it yesterday as an initial code snippet. Things need to be cleared and re-sorted in the next weeks :) but thank you for checking the code and making some changes. Will review it and merge the necessary stuff into my project.

**Comment by shor-ty** [comment]
I will merge the commits but I am not sure about your "folder" names. 
Why do we need "source/DIY.../*.C". In my opinion we should keep:

/ArduinoFolder/<files>

However, I would go to put all classes into:

/ArduinoFolder/<src>/<className>//<SourceHeaderFiles>

**Comment by ElectronicsArchiver** [comment]
I found it by searching for 'recently updated'.

Are you not using the Arduino IDE?

As you are using '.ino' files instead of '.cpp' I assumed you were using it.

The Arduino IDE requires you to have your '.ino' file in a folder with the same name as the file.

This is why using PlatformIO or a manual setup is preferred.

In general it is recommended to have source code in a simple 'Source' 'source' 'src' folder, with subfolder as needed.

In the case of a non-library c++ project for example I'd suggest a 'Source/Include' folder.

**Comment by shor-ty** [comment]
I merged your pull request (as you already noticed, i guess). 

I am using Arduino IDE as well as vim (it is my favorite editor). Today I checked how the compiler is called. Seems to be a special one rather than simply using g++. I kept your Arduino folder stuff but moved the files (except of the *.ino one) into a src file. Seems to work quite good.

Thank you for your hints and the merge request!.
Tobi

**Comment by ElectronicsArchiver** [comment]
Compiling for avr controller uses a AVR flavor of GCC
(sadly not very up to date with normal C++ / std)
as well as avrdude to load it onto the controller.

**Pull request merged**
